spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useSSL=false
    username: root
    password: aaaa
    tomcat:
      initialSize: 1
      min-idle: 1
      max-idle: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  jackson:
    default-property-inclusion: non_null
logging:
  file: logs/doctor.log
  level:
    root: warn
    org.nutz.dao.impl: WARN
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
---
spring:
  profiles: dev
